version: 2
jobs:
  build:
    machine: true
    
    steps:
      - checkout

      # build the application image
      - run: docker build -t amitrke/node-appengine:$CIRCLE_BRANCH node-appengine

      # deploy the image
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push amitrke/node-appengine:$CIRCLE_BRANCH