version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the node application image
      - run: docker build -t amitrke/node-appengine:$CIRCLE_BRANCH node-appengine

      # deploy the node image
      #- run: docker push amitrke/node-appengine:$CIRCLE_BRANCH

      # build the java application image
      - run: docker build -t amitrke/java-appengine:$CIRCLE_BRANCH java-appengine

      # deploy the java image
      #- run: docker push amitrke/java-appengine:$CIRCLE_BRANCH